<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <StartupObject>mapf.Program</StartupObject>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.104.2" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Layouts\Average %28Expected%29.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Layouts\Large %28Possible%29 - Copy.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Layouts\Large %28Possible%29.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Layouts\Layout 2025-04-23.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Layouts\Layout 2025-04-23Simplified.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Layouts\Layout.xlsx">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>